version: "3.8"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      HOST: "ganache"
      PORT: "8545"
    depends_on:
      - ganache  

  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - 8545:8545